### ISSUE TITLE
Let me know if this works

### ISSUE THREAD

**Issue by yuriyt2** [yuriyt2/mp3_app#1]
My idea is to access a cloud service (not sure which one yet) to get a folder of mp3s and allow a user to play them.  I will use node player and hopefully the api of the cloud storage site.

**Comment by jasonseminara** [comment]
This is kinda thin. 

Is this an application? What exactly are the use cases? Why is this different than just sharing links to youtube?

**Comment by yuriyt2** [comment]
The idea is to have access to your library of music and not have to access a third party (besides the storage site).  The application would take each user's sessions and link them to a user's personal directory of music.  The app would allow you to choose what music you play and maybe also make a playlist.  The use case is something like this: you are at a party but don't have access to your music collection.  My app would allow you to log in, access your music, and play what you want.

**Comment by jasonseminara** [comment]
approved.
